version: '3.8'

# This file defines two services: The db service and the web service.
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=supernextwebb
      - POSTGRES_PASSWORD=p@55DNS
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    container_name: DNA_backend
    volumes:
      - .:/DNA_backend
    ports:
      - "8002:80"
    depends_on:
      - db