# Generated by Django 3.0.8 on 2020-07-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_loan_record',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
