# Generated by Django 3.1 on 2020-08-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='balance_to_pay',
            field=models.IntegerField(blank=True, default=models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='loan_record',
            name='due_date',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
    ]
