# Generated by Django 2.2.8 on 2020-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='balance_to_pay',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
