# Generated by Django 3.1 on 2020-08-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
