# Generated by Django 3.0.8 on 2020-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200722_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_loan_record',
            name='due_date',
            field=models.DateField(auto_now=True),
        ),
    ]
