# Generated by Django 3.0.8 on 2020-08-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200801_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_record',
            name='interest_rate',
            field=models.CharField(max_length=200),
        ),
    ]
