# Generated by Django 2.2.8 on 2020-08-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200828_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
