# Generated by Django 3.1 on 2020-08-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200828_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
