# Generated by Django 3.1 on 2020-08-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200822_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='balance_to_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan_record',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
