# Generated by Django 3.1 on 2020-08-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200829_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='due_date',
            field=models.DateField(),
        ),
    ]
