# Generated by Django 3.0.8 on 2020-08-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200801_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='balance_to_pay',
            field=models.IntegerField(blank=True, max_length=200),
        ),
    ]
