# Generated by Django 2.2.8 on 2020-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200828_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan_record',
            name='balance_to_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
