# Generated by Django 2.2.8 on 2020-08-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200828_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_record',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
