# Generated by Django 2.2.14 on 2020-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
